server:
  port: 9001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quizhub_auth
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yUXVpekh1YkF1dGhTZXJ2aWNlMTIzNDU2Nzg5
  expiration: 86400000

refresh-token:
  expiration: 604800000   # 7 days